[package]
name = "spawn_scene"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.10"
bevy = {version = "0.7", default-features = false}
bevy_godot = {path = "../../core"}